language: python
python:
  - 2.7
services:
    - mysql
install:
    - pip install cython
    - pip install PIL==1.1.7 --allow-external PIL --allow-unverified PIL
    - pip install pypdf --allow-external pypdf --allow-unverified pypdf
    - pip install -r requirements.txt -r test_requirements.txt .
script:  py.test
before_install:
  - ./.travis_before_install.sh
notifications:
    irc:
        channels:
            - "irc.freenode.org#majerteam-travis"
        on_success: change
